/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiServicesRouteImport } from './routes/ai-services'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CbtRouteImport } from './routes/cbt'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as KnowledgeBaseRouteImport } from './routes/knowledge-base'
import { Route as MoodleDevelopmentRouteImport } from './routes/moodle-development'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as AboutProcessRouteImport } from './routes/about.process'
import { Route as AboutTechnologyRouteImport } from './routes/about.technology'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as ServicesServiceIdRouteImport } from './routes/services.$serviceId'
import { Route as ServicesAiLearningRouteImport } from './routes/services.ai-learning'
import { Route as ServicesMoodleConsultingRouteImport } from './routes/services.moodle-consulting'
import { Route as ServicesMoodleCustomizationRouteImport } from './routes/services.moodle-customization'
import { Route as ServicesMoodleImplementationRouteImport } from './routes/services.moodle-implementation'
import { Route as SolutionsSolutionIdRouteImport } from './routes/solutions.$solutionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiServicesRoute = AiServicesRouteImport.update({
  id: '/ai-services',
  path: '/ai-services',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CbtRoute = CbtRouteImport.update({
  id: '/cbt',
  path: '/cbt',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodleDevelopmentRoute = MoodleDevelopmentRouteImport.update({
  id: '/moodle-development',
  path: '/moodle-development',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutProcessRoute = AboutProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => AboutRoute,
} as any)
const AboutTechnologyRoute = AboutTechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => AboutRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/$serviceId',
  path: '/$serviceId',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAiLearningRoute = ServicesAiLearningRouteImport.update({
  id: '/ai-learning',
  path: '/ai-learning',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesMoodleConsultingRoute =
  ServicesMoodleConsultingRouteImport.update({
    id: '/moodle-consulting',
    path: '/moodle-consulting',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesMoodleCustomizationRoute =
  ServicesMoodleCustomizationRouteImport.update({
    id: '/moodle-customization',
    path: '/moodle-customization',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesMoodleImplementationRoute =
  ServicesMoodleImplementationRouteImport.update({
    id: '/moodle-implementation',
    path: '/moodle-implementation',
    getParentRoute: () => ServicesRoute,
  } as any)
const SolutionsSolutionIdRoute = SolutionsSolutionIdRouteImport.update({
  id: '/$solutionId',
  path: '/$solutionId',
  getParentRoute: () => SolutionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/ai-services': typeof AiServicesRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/cbt': typeof CbtRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/downloads': typeof DownloadsRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/moodle-development': typeof MoodleDevelopmentRoute
  '/services': typeof ServicesRouteWithChildren
  '/solutions': typeof SolutionsRouteWithChildren
  '/trust': typeof TrustRoute
  '/updates': typeof UpdatesRoute
  '/about/process': typeof AboutProcessRoute
  '/about/technology': typeof AboutTechnologyRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/services/ai-learning': typeof ServicesAiLearningRoute
  '/services/moodle-consulting': typeof ServicesMoodleConsultingRoute
  '/services/moodle-customization': typeof ServicesMoodleCustomizationRoute
  '/services/moodle-implementation': typeof ServicesMoodleImplementationRoute
  '/solutions/$solutionId': typeof SolutionsSolutionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/ai-services': typeof AiServicesRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/cbt': typeof CbtRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/downloads': typeof DownloadsRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/moodle-development': typeof MoodleDevelopmentRoute
  '/services': typeof ServicesRouteWithChildren
  '/solutions': typeof SolutionsRouteWithChildren
  '/trust': typeof TrustRoute
  '/updates': typeof UpdatesRoute
  '/about/process': typeof AboutProcessRoute
  '/about/technology': typeof AboutTechnologyRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/services/ai-learning': typeof ServicesAiLearningRoute
  '/services/moodle-consulting': typeof ServicesMoodleConsultingRoute
  '/services/moodle-customization': typeof ServicesMoodleCustomizationRoute
  '/services/moodle-implementation': typeof ServicesMoodleImplementationRoute
  '/solutions/$solutionId': typeof SolutionsSolutionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/ai-services': typeof AiServicesRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/cbt': typeof CbtRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/downloads': typeof DownloadsRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/moodle-development': typeof MoodleDevelopmentRoute
  '/services': typeof ServicesRouteWithChildren
  '/solutions': typeof SolutionsRouteWithChildren
  '/trust': typeof TrustRoute
  '/updates': typeof UpdatesRoute
  '/about/process': typeof AboutProcessRoute
  '/about/technology': typeof AboutTechnologyRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/services/ai-learning': typeof ServicesAiLearningRoute
  '/services/moodle-consulting': typeof ServicesMoodleConsultingRoute
  '/services/moodle-customization': typeof ServicesMoodleCustomizationRoute
  '/services/moodle-implementation': typeof ServicesMoodleImplementationRoute
  '/solutions/$solutionId': typeof SolutionsSolutionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-services'
    | '/blog'
    | '/careers'
    | '/case-studies'
    | '/cbt'
    | '/contact'
    | '/docs'
    | '/downloads'
    | '/faq'
    | '/industries'
    | '/knowledge-base'
    | '/moodle-development'
    | '/services'
    | '/solutions'
    | '/trust'
    | '/updates'
    | '/about/process'
    | '/about/technology'
    | '/products/$productId'
    | '/services/$serviceId'
    | '/services/ai-learning'
    | '/services/moodle-consulting'
    | '/services/moodle-customization'
    | '/services/moodle-implementation'
    | '/solutions/$solutionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-services'
    | '/blog'
    | '/careers'
    | '/case-studies'
    | '/cbt'
    | '/contact'
    | '/docs'
    | '/downloads'
    | '/faq'
    | '/industries'
    | '/knowledge-base'
    | '/moodle-development'
    | '/services'
    | '/solutions'
    | '/trust'
    | '/updates'
    | '/about/process'
    | '/about/technology'
    | '/products/$productId'
    | '/services/$serviceId'
    | '/services/ai-learning'
    | '/services/moodle-consulting'
    | '/services/moodle-customization'
    | '/services/moodle-implementation'
    | '/solutions/$solutionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-services'
    | '/blog'
    | '/careers'
    | '/case-studies'
    | '/cbt'
    | '/contact'
    | '/docs'
    | '/downloads'
    | '/faq'
    | '/industries'
    | '/knowledge-base'
    | '/moodle-development'
    | '/services'
    | '/solutions'
    | '/trust'
    | '/updates'
    | '/about/process'
    | '/about/technology'
    | '/products/$productId'
    | '/services/$serviceId'
    | '/services/ai-learning'
    | '/services/moodle-consulting'
    | '/services/moodle-customization'
    | '/services/moodle-implementation'
    | '/solutions/$solutionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  AiServicesRoute: typeof AiServicesRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  CbtRoute: typeof CbtRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  DownloadsRoute: typeof DownloadsRoute
  FaqRoute: typeof FaqRoute
  IndustriesRoute: typeof IndustriesRoute
  KnowledgeBaseRoute: typeof KnowledgeBaseRoute
  MoodleDevelopmentRoute: typeof MoodleDevelopmentRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SolutionsRoute: typeof SolutionsRouteWithChildren
  TrustRoute: typeof TrustRoute
  UpdatesRoute: typeof UpdatesRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-services': {
      id: '/ai-services'
      path: '/ai-services'
      fullPath: '/ai-services'
      preLoaderRoute: typeof AiServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cbt': {
      id: '/cbt'
      path: '/cbt'
      fullPath: '/cbt'
      preLoaderRoute: typeof CbtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moodle-development': {
      id: '/moodle-development'
      path: '/moodle-development'
      fullPath: '/moodle-development'
      preLoaderRoute: typeof MoodleDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/process': {
      id: '/about/process'
      path: '/process'
      fullPath: '/about/process'
      preLoaderRoute: typeof AboutProcessRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/technology': {
      id: '/about/technology'
      path: '/technology'
      fullPath: '/about/technology'
      preLoaderRoute: typeof AboutTechnologyRouteImport
      parentRoute: typeof AboutRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ai-learning': {
      id: '/services/ai-learning'
      path: '/ai-learning'
      fullPath: '/services/ai-learning'
      preLoaderRoute: typeof ServicesAiLearningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/moodle-consulting': {
      id: '/services/moodle-consulting'
      path: '/moodle-consulting'
      fullPath: '/services/moodle-consulting'
      preLoaderRoute: typeof ServicesMoodleConsultingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/moodle-customization': {
      id: '/services/moodle-customization'
      path: '/moodle-customization'
      fullPath: '/services/moodle-customization'
      preLoaderRoute: typeof ServicesMoodleCustomizationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/moodle-implementation': {
      id: '/services/moodle-implementation'
      path: '/moodle-implementation'
      fullPath: '/services/moodle-implementation'
      preLoaderRoute: typeof ServicesMoodleImplementationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/solutions/$solutionId': {
      id: '/solutions/$solutionId'
      path: '/$solutionId'
      fullPath: '/solutions/$solutionId'
      preLoaderRoute: typeof SolutionsSolutionIdRouteImport
      parentRoute: typeof SolutionsRoute
    }
  }
}

interface AboutRouteChildren {
  AboutProcessRoute: typeof AboutProcessRoute
  AboutTechnologyRoute: typeof AboutTechnologyRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutProcessRoute: AboutProcessRoute,
  AboutTechnologyRoute: AboutTechnologyRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface ServicesRouteChildren {
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  ServicesAiLearningRoute: typeof ServicesAiLearningRoute
  ServicesMoodleConsultingRoute: typeof ServicesMoodleConsultingRoute
  ServicesMoodleCustomizationRoute: typeof ServicesMoodleCustomizationRoute
  ServicesMoodleImplementationRoute: typeof ServicesMoodleImplementationRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  ServicesAiLearningRoute: ServicesAiLearningRoute,
  ServicesMoodleConsultingRoute: ServicesMoodleConsultingRoute,
  ServicesMoodleCustomizationRoute: ServicesMoodleCustomizationRoute,
  ServicesMoodleImplementationRoute: ServicesMoodleImplementationRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface SolutionsRouteChildren {
  SolutionsSolutionIdRoute: typeof SolutionsSolutionIdRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsSolutionIdRoute: SolutionsSolutionIdRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  AiServicesRoute: AiServicesRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  CbtRoute: CbtRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  DownloadsRoute: DownloadsRoute,
  FaqRoute: FaqRoute,
  IndustriesRoute: IndustriesRoute,
  KnowledgeBaseRoute: KnowledgeBaseRoute,
  MoodleDevelopmentRoute: MoodleDevelopmentRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SolutionsRoute: SolutionsRouteWithChildren,
  TrustRoute: TrustRoute,
  UpdatesRoute: UpdatesRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
